version: "3.5"
services:
  auth:
    env_file:
      - ./.envs/auth/.env
    container_name: auth.floweryroad-api
    build:
      context: ./auth
    volumes:
      - "./auth:/auth"
    ports:
      - "8000:8000"
    entrypoint: "python3 manage.py runserver 0.0.0.0:8000"
  auth-database:
    env_file: 
      - ./.envs/auth/db.env
    image: postgres:12.2-alpine
    container_name: database.auth.floweryroad-api
    volumes:
      - database.auth.floweryroad-api:/var/lib/postgresql/data


  app:
    env_file:
      - ./.envs/app/.env
    container_name: app.floweryroad-api
    build:
      context: ./app
    volumes:
      - "./app:/app"
    ports:
      - "8001:8001"
    entrypoint: "python3 manage.py runserver 0.0.0.0:8001"
  app-database:
    env_file: 
      - ./.envs/app/db.env
    image: postgres:12.2-alpine
    container_name: database.app.floweryroad-api
    volumes:
      - database.app.floweryroad-api:/var/lib/postgresql/mydata

volumes:
  database.app.floweryroad-api:
  database.auth.floweryroad-api:
