apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: api-gateway
  namespace: floweryroad
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    http:
      paths:
      - path: /auth
        backend:
          serviceName: "auth"
          servicePort: 80
      - path: /app
        backend:
          serviceName: "app"
          servicePort: 80
