apiVersion: v1
kind: Service
metadata:
  name: db.auth
spec:
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
---
apiVersion: v1
kind: Endpoints
metadata:
  name: db.auth
subsets:
  - addresses:
      - ip: 10.0.2.2
    ports:
      - port: 5432
---
apiVersion: v1
kind: Service
metadata:
  name: db.app
spec:
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
---
apiVersion: v1
kind: Endpoints
metadata:
  name: db.app
subsets:
  - addresses:
      - ip: 10.0.2.2
    ports:
      - port: 5431
